services:
  - type: web
    name: xml-images
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn.conf.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: REDIS_URL
        fromService:
          type: redis
          name: XML # <-- Upewnij się, że ta nazwa jest taka sama jak w usłudze Redis poniżej
      - key: GEMINI_API_KEY
        fromSecret: true

  - type: redis
    name: XML # <-- Nadaj nazwę swojej usłudze Redis
    plan: free
    ipAllowList: [] # Opcjonalnie: ogranicz dostęp po IP
